### ISSUE TITLE
Does `default: []` definition in `schema.db` work?

### ISSUE THREAD

**Issue by josephschito** [nulldb/nulldb#115]
If I have a schema like:
```ruby
...
create_table "some_table", id: false, force: :cascade do |t|
  t.integer "some_field", default: 1
end
...
```
I have an Object like
```ruby
SomeTable.new.some_field # => nil
```

So I have to add something like

```ruby
...
after_initialize :set_some_field

# and

def set_some_field
  self.some_field = 1
end
...
```

Do you know if it's possible to add this functionality?

**Comment by cabello** [comment]
Hi, care to elaborate or provide more context? Did you try what you are suggesting, what happened?

**Comment by cabello** [comment]
I think so, looking at the code, the following line passes all column parameters to a new class: https://github.com/nulldb/nulldb/blob/11269e9bd7d6e0d4b9b9e3aabb0540af242100aa/lib/active_record/connection_adapters/nulldb_adapter/core.rb#L166

If you implement something to handle the defaults, it could return that value instead of null:

https://github.com/nulldb/nulldb/blob/11269e9bd7d6e0d4b9b9e3aabb0540af242100aa/lib/active_record/connection_adapters/nulldb_adapter/column.rb

And here you can see the rails implementation of column that receives the default parameter:
https://github.com/rails/rails/blob/d44e786d216f82584c7752ffee91ef4d5bea14ba/activerecord/lib/active_record/connection_adapters/column.rb
